# VPC Setup
aws cloudformation create-stack-set --stack-set-name durability-recovery --template-body file:///Users/nb732834/lab/udacity/cloud-arch-nd/1-durability-recovery/cloudformation/vpc.yaml
aws cloudformation create-stack-instances --stack-set-name durability-recovery --accounts '["000000000000"]' --regions '["us-east-1"]' --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1 --parameter-overrides ParameterKey=VpcName,ParameterValue=Primary ParameterKey=VpcCIDR,ParameterValue=10.1.0.0/16 ParameterKey=PublicSubnet1CIDR,ParameterValue=10.1.10.0/24 ParameterKey=PublicSubnet2CIDR,ParameterValue=10.1.11.0/24 ParameterKey=PrivateSubnet1CIDR,ParameterValue=10.1.20.0/24 ParameterKey=PrivateSubnet2CIDR,ParameterValue=10.1.21.0/24
aws cloudformation create-stack-instances --stack-set-name durability-recovery --accounts '["000000000000"]' --regions '["us-east-2"]' --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1 --parameter-overrides ParameterKey=VpcName,ParameterValue=Secondary ParameterKey=VpcCIDR,ParameterValue=10.2.0.0/16 ParameterKey=PublicSubnet1CIDR,ParameterValue=10.2.10.0/24 ParameterKey=PublicSubnet2CIDR,ParameterValue=10.2.11.0/24 ParameterKey=PrivateSubnet1CIDR,ParameterValue=10.2.20.0/24 ParameterKey=PrivateSubnet2CIDR,ParameterValue=10.2.21.0/24

# RDS setup in Active region
aws cloudformation create-stack-set --stack-set-name rds-active-durability-recovery --template-body file:///Users/nb732834/lab/udacity/cloud-arch-nd/1-durability-recovery/cloudformation/rds.yaml
aws cloudformation create-stack-instances --stack-set-name rds-active-durability-recovery --accounts '["000000000000"]' --regions '["us-east-1"]' --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1 --parameter-overrides ParameterKey=DBName,ParameterValue=udacity  ParameterKey=DBUser,ParameterValue=udacity ParameterKey=DBPassword,ParameterValue=ud2c1ty123 ParameterKey=DBAllocatedStorage,ParameterValue=5 ParameterKey=DBInstanceClass,ParameterValue=db.t2.micro ParameterKey=DBSecurityGroups,ParameterValue=sg-076d7ca3c3c8b3243 ParameterKey=MultiAZ,ParameterValue=true ParameterKey=DBSubnetGroupName,ParameterValue=udarr-rds-subnet

# RDS read replica setup in standby region
aws cloudformation create-stack-set --stack-set-name rds-standby-durability-recovery --template-body file:///Users/nb732834/lab/udacity/cloud-arch-nd/1-durability-recovery/cloudformation/rds-read-replica.yaml
aws cloudformation create-stack-instances --stack-set-name rds-standby-durability-recovery --accounts '["000000000000"]' --regions '["us-east-2"]' --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1 --parameter-overrides ParameterKey=MasterDB,ParameterValue=arn:aws:rds:us-east-1:000000000000:db:smhtiuzv4ep49y ParameterKey=DBSecurityGroups,ParameterValue=sg-09ab345c5efc12065 ParameterKey=DBSubnetGroupName,ParameterValue=UDARR-RDS-Subnet ParameterKey=MultiAZ,ParameterValue=true

